name: Simple Math CI

on:
  workflow_dispatch:
    inputs: 
        var_A:
            description: 'Giá trị A'
            required: true
            default: "1"
        var_B:
            description: 'Giá trị B'
            required: true
            default: "2"
        var_C:
            description: 'Giá trị C'
            required: true
            type: choice
            options:
              - "1"
              - "2"
              - "3"
              - "4"
              - "5"
            default: "2"
  push:
    branches:
      - main
    


jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Say hello
        run: |
            result=$((${{ github.event.inputs.var_A }} + ${{ github.event.inputs.var_B }}))
            echo "The result of A + B is: $result" 
    