name: Simple Math CI

on:
  workflow_dispatch:
    inputs: 
        var_A:
            description: 'Giá trị A'
            required: true
            default: "1"
        var_B:
            description: 'Giá trị B'
            required: true
            default: "2"
        var_C:
            description: 'Giá trị C'
            required: true
            type: choice
            options:
              - "1"
              - "2"
              - "3"
              - "4"
              - "5"
            default: "2"
  push:
    branches:
      - main
  schedule:
    - cron: "1 20 * * *"
  repository_dispatch:
    types: [run-test, deploy, sync-data] # Chạy hàng ngày vào lúc 00:00

env:
  default_A: "10"  
  default_B: ${{ vars.VarB }}
  default_C: ${{ secrets.SecretC }} 


jobs:
  say-hello:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.say-hello.outputs.result }}
    steps:
      - name: Step 1 - Say hello
        id: say-hello
        env:
          var_A: ${{ github.event.inputs.var_A || env.default_A }}
          var_B: ${{ github.event.inputs.var_B || env.default_B }}
          var_C: ${{ github.event.inputs.var_C || env.default_C }}
        run: |
            result=$(($var_A + $var_B))
            echo "The result of A + B is: $result" 
            echo "The value of C is: $var_C"
            echo "result=$result" >> $GITHUB_OUTPUT
      - name: Step 2 - Say goodbye
        run: echo "Goodbye, world!"
      - name: Step 3 - Final step
        run: echo "This is the final step of the workflow."
  job-two:
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: Step 1 - Say hello
        env:
          var_A: ${{ github.event.inputs.var_A || env.default_A }}
          var_BB: ${{needs.say-hello.outputs.result}}
        run: |
            result=$(($var_A + $var_BB))
            echo "The result of A + B is: $result" 
            echo "The value of C is: $var_C"
      - name: Step 2 - Say goodbye
        run: echo "Goodbye, world!"
      - name: Step 3 - Final step
        run: echo "This is the final step of the workflow."
  job-three:
    runs-on: ubuntu-latest
    needs: say-hello
    if: needs.say-hello.outputs.result == '15' # Chỉ chạy nếu kết quả của job say-hello là 3
    steps:
      - name: Step 1 - Say hello
        env:
          var_A: ${{ github.event.inputs.var_A || env.default_A }}
        run: |
            result=$(($var_A + ${{needs.say-hello.outputs.result}}))
            echo "The result of A + B is: $result" 
            echo "The value of C is: $var_C"
      - name: Step 2 - Say goodbye
        run: echo "Goodbye, world!"
      - name: Step 3 - Final step
        run: echo "This is the final step of the workflow."
      - name: Step 1.5 - Upload log
        uses: actions/upload-artifact@v4
        with:
          name: math-log
          path: log.txt
    